### ISSUE TITLE
how i get path without package prefix by pkger.Walk()

### ISSUE THREAD

**Issue by mlboy** [markbates/pkger#118]
when i using pkger.Walk()

i print path and get this result :

"app:/template/xxx.html"

how i get "/template/xxx.html"  i need not  "app:" part

**Comment by dschissler** [comment]
The obvious hack is just to split the string using the `:` delimiter, but of course we'd rather learn something :).

**Comment by mlboy** [comment]
> The obvious hack is just to split the string using the `:` delimiter, but of course we'd rather learn something :).

I do it now, but I don't feel beautiful enough
