### ISSUE TITLE
Error when a directory contains no `.go` or `go.mod` files

### ISSUE THREAD

**Issue by aperezg** [markbates/pkger#22]
Hi Mark,

More than issue is a doubt to know if I'm doing wrong while use your library. I try to follow your examples and I've the follow structure:

<pre>
├── cmd
│   ├── reader
│   │   ├── main.go
├── files
│   ├── swapi.go
├── reader.go
├── go.mod
</pre>

The `reader.go` code:

```go
package pkg

import (
	"fmt"
	"io"
	"os"
	"time"

	"github.com/markbates/pkger"
)

func ReadCsv() error {
	f, err := pkger.Open("/files/swapi.csv")
	if err != nil {
		return err
	}
	defer f.Close()

	data, err := f.Stat()
	if err != nil {
		return err
	}

	fmt.Println("File name: ", data.Name())
	fmt.Println("File size: ", data.Size())
	fmt.Println("File mode: ", data.Mode())
	fmt.Println("Modification time: ", data.ModTime().Format(time.RFC3339))

	fmt.Println()
	if _, err := io.Copy(os.Stdout, f); err != nil {
		return err
	}

	return nil

}
```

So when I executed the code `go run cmd/reader/main.go` everything is fine, but if I move the `reader.go` inside another directory:

<pre>
├── cmd
│   ├── reader
│   │   ├── main.go
├── files
│   ├── swapi.go
├── pkg
│   ├── reader.go
├── go.mod
</pre>

And I executed again the code `go run cmd/reader/main.go` I got the follow error:

<pre>
2019/11/09 15:57:49 exit status 1: go: cannot find main module; see 'go help modules'

2019/11/09 15:57:49 open /files/swapi.csv: no such file or directory
exit status 1
</pre>

I understand if the static files are in a level without any `.go` file that indicate a package, then the pkger can't find the `go.mod`. Because if I add a simple `sample.go` in the root folder, to the same level that `files` directory, then the application works fine.

Could you help me to understand what is my wrong here?

**Comment by markbates** [comment]
Can you make sure you’re using 0.10.1? Also if you can paste the results of pkger info and pkger parse, that would be helpful. Thanks.

**Comment by aperezg** [comment]
Yes, I currently using the version `0.10.1`

**go.mod**
```
module github.com/friendsofgo/sample-pkgr

go 1.13

require github.com/markbates/pkger v0.10.1
```

**pkger info**
<pre>
 pkger info
2019/11/09 16:27:53 exit status 1: go: cannot find main module; see 'go help modules'

2019/11/09 16:27:53 exit status 1: build .: cannot find module for path .
</pre>

**pkger parse**
<pre>
 pkger parse
2019/11/09 16:28:40 exit status 1: go: cannot find main module; see 'go help modules'

2019/11/09 16:28:41 exit status 1: build .: cannot find module for path .
</pre>

If I add a go file to the same level of the `files` directory the output is corret, and is:

**pkger info**
<pre>
{
 "Dir": "/Users/aperez/dev/projects/gist/pkgr",
 "ImportPath": "github.com/friendsofgo/sample-pkgr",
 "Module": {
  "path": "github.com/friendsofgo/sample-pkgr",
  "main": true,
  "dir": "/Users/aperez/dev/projects/gist/pkgr",
  "go_mod": "",
  "go_version": ""
 },
 "Name": "sample"
}
</pre>

**pkger parse**
<pre>
{
 ".": [
  {
   "file": {
    "Abs": "/Users/aperez/dev/projects/gist/pkgr/files/swapi.csv",
    "Path": {
     "pkg": "github.com/friendsofgo/sample-pkgr",
     "name": "/files/swapi.csv"
    },
    "Here": {
     "Dir": "/Users/aperez/dev/projects/gist/pkgr/pkg",
     "ImportPath": "github.com/friendsofgo/sample-pkgr/pkg",
     "Module": {
      "path": "github.com/friendsofgo/sample-pkgr",
      "main": true,
      "dir": "/Users/aperez/dev/projects/gist/pkgr",
      "go_mod": "",
      "go_version": ""
     },
     "Name": "reader"
    }
   },
   "pos": {
    "Filename": "/Users/aperez/dev/projects/gist/pkgr/pkg/reader.go",
    "Offset": 131,
    "Line": 13,
    "Column": 23
   },
   "type": "pkger.Open",
   "value": "github.com/friendsofgo/sample-pkgr:/files/swapi.csv"
  }
 ]
}
</pre>

**Comment by aperezg** [comment]
Mark,

I've debugged the code and I found the problem:
https://github.com/markbates/pkger/blob/master/here/dir.go#L34

When the `go list -json` fails, you try to continue find the go.modules, but then you try to navigate to the directory:
https://github.com/markbates/pkger/blob/master/here/dir.go#L42

The result is try to find the go.mod outside of the repository itself.

**Comment by aperezg** [comment]
I think that one way to solve that, is first of all checking is there any go.mod in the current directory if exists, then execute the `go list -json` to take advantage of the unmarshalling if any go file exist, if is not then we can build a constructor for `Info` struct with the require information.

What do you think? I could work on it if you want to try to show a solution.

**Comment by markbates** [comment]
Go for it! I’d love help with that. It’s frustrating the go tooling falls down like that even though it’s in a module. 

--
Mark Bates

**Comment by markbates** [comment]
@aperezg thanks for this. I had to make a couple of changes to your PR, and along the way, I ended up cleaning up more. :) You're commits are in `v0.11.0`. 

I also added a `-o` flag so you can specify the directory of the `pkged.go` file.

```bash
$ pkger -o cmd/reader
```

```go
// cmd/reader/pkged.go
package main

// Pkger stuff here
```

**Comment by aperezg** [comment]
Perfect!👌🏼 The new option it's great to avoid unnecessary explicit import 😊 Thanks!
