### ISSUE TITLE
Cross compile Osx > Win - errors on Windows 

### ISSUE THREAD

**Issue by tarkh** [markbates/pkger#37]
Hi!
Thanx for cool package!
Btw, I've faced issue while cross compiling from OSX to Win.
My steps to reproduce:

1. Went to `~/go/src/github.com/markbates/pkger/examples/open/pkger`
2. Created `win.sh` script with `chmod +x` and following content:
```bash
RUN=$(`
  export CGO_ENABLED=1
  export GOOS="windows"
  export GOARCH="amd64"

  go build
)
echo $RUN
```
3. Ran the cross compiler `./win.sh`
4. Got `app.exe` file and copied it to Win 7 on Parallels
5. Executed `app.exe` in `cmd.exe` and got an error:
```terminal
2019/11/19 14:48:10 exec: "go": executable file not found in %PATH%: "go env GOMOD":
2019/11/19 14:48:10 open \public\index.html: The system cannot find the path specified.
```

**Comment by markbates** [comment]
You need to run pkger before go build to generate the pkged.go file. Without that step this is expected. The file doesn’t exist in the binary. 

--
Mark Bates

**Comment by tarkh** [comment]
Thank you, Mark! My mistake. However, it solves the problem with reading embedded file, but first line still there with exec go not found:
```terminal
2019/11/19 19:27:58 exec: "go": executable file not found in %PATH%: "go env GOMOD":
Name:  index.html
Size:  257
Mode:  -rw-r--r--
ModTime:  2019-11-18 22:51:59.765687024 +0300 MSK
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width" />
        <title>HI</title>
    </head>
    <body>
        HELLO
        <img src="/images/img1.png" alt=""/>
    </body>
</html>
```

**Comment by markbates** [comment]
That’s a debugging line that will be removed in the future. It isn’t anything to worry about.
