### ISSUE TITLE
executable size is too big compared to what is being included

### ISSUE THREAD

**Issue by mmrath** [markbates/pkger#42]
Only one file of size (< 1K) in a folder with 3 levels of nesting is adding 5 MB to the generated executable. Is that expected?

**Comment by markbates** [comment]
Without a reproducible example, I can’t answer the question.

**Comment by mmrath** [comment]
[pkger-example.zip](https://github.com/markbates/pkger/files/3877812/pkger-example.zip)
Here is a sample project.

`go build demo/demo_main1.go`
`go build demo/demo_main2.go`

produced two executable with huge size diff

**Comment by markbates** [comment]
As far as I can tell the problem might be that you're including `/demo` with Pkger, which bundles the folder, and all below, which might contain a previous built binary. At least, that's what I found when running your example.

I trimmed yours down to the following tree:

```bash
.
├── bin
│   ├── with
│   └── without
├── go.mod
├── go.sum
├── main.go
├── pkged.go
└── res
    └── test
        └── test1.txt

3 directories, 7 files
```

And revised your `main.go` to only capture the `/res` directory:

```go
package main

import (
	"fmt"
	"os"
	"text/tabwriter"
	"time"

	"github.com/markbates/pkger"
)

func main() {
	err := run()
	if err != nil {
		panic(err)
	}
}

func run() error {
	w := tabwriter.NewWriter(os.Stdout, 0, 0, 0, ' ', tabwriter.Debug)
	defer w.Flush()

	return pkger.Walk("/res", func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		fmt.Fprintf(w,
			"%s \t %d \t %s \t %s \t\n",
			info.Name(),
			info.Size(),
			info.Mode(),
			info.ModTime().Format(time.RFC3339),
		)

		return nil
	})

}
```

The I generated the first binary, without having run `Pkger` first.

```bash
$ go build -o bin/without
```

The I ran `pkger` and built a new binary with the bundled assets.

```bash
$ pkger
$ go build -o bin/with
```

That resulted in two binaries that weren't that far off in size:

```bash
total 30672
-rwxr-xr-x  1 markbates  staff   7.6M Nov 22 17:00 with
-rwxr-xr-x  1 markbates  staff   7.3M Nov 22 16:58 without
```

If you run `pkger list` you'll see a list of all the files Pkger will pack, that might help you track down your problem further.

I'm closing this ticket, as I believe to it be an environmental issue. Should the problem persist, please re-open.

**Comment by mmrath** [comment]
[pkger-example.zip](https://github.com/markbates/pkger/files/3882038/pkger-example.zip)
I don't think this is environmental issue. I am able to replicate on both windows and Mac. See the attached whcih also contains binaries. One of the exe is only 2.1 for me.

**Comment by mmrath** [comment]
@markbates I am not able to reopen this issue but I think this issue is not resolved.

**Comment by markbates** [comment]
Please read my description of what is happening. 

Run pkger list and provide its output. 

Provide a repo, as working with zips is difficult. 

Finally provide exact step by step instructions. 

Alternatively a Dockerfile that reproduces the issue. 

Without that I can’t reproduce.
