### ISSUE TITLE
How to save included files/dirs from binary to outer folder?

### ISSUE THREAD

**Issue by koddr** [markbates/pkger#43]
Hello.

I write simple CLI script, which make some automation for creating web server (based on `net/http`). I include folder with completed app structure via pkger to binary, but how to save (or copy) packed app from binary to outer folder?

I read README, but not sure it's possible?

Something like `ioutil.WriteFile(fileOutput, fileInput, 0644)` will be great, but doesn't work with `pkger.Open()` file.

**Comment by markbates** [comment]
I don’t quite understand the question, I think you want to take the contents of a pkged folder and write back to disk. 

If so, pkger.Walk works just like filepath. Walk. Walk the folder, open the file, create the new file, use io.Copy, close the files and repeat. 

The workflow is identical to using the standard library. 

If, however, you question is does that utility exist for pkger? The answer is no.

**Comment by koddr** [comment]
@markbates thanks for answer.

> If so, pkger.Walk works just like filepath. Walk. Walk the folder, open the file, create the new file, use io.Copy, close the files and repeat.

Yes, this works only if I run binary from my app folder. But if I turn them to another folder — only shows `no such file or directory` for folder I include to binary (by `pkger.Include("/my/dir")`).

**Comment by markbates** [comment]
You'll you need to provide a reproducible example for me to be able to help you more. Thanks.

**Comment by koddr** [comment]
@markbates I found reason of my errors!
I don't run `pkger` before try to execute my CLI script.

Thanks for participating 👍
