### ISSUE TITLE
"pkger parse" does not detect pkger.Open(), pkger.Stat() when called with concatenated strings

### ISSUE THREAD

**Issue by snehagundura** [markbates/pkger#45]
I have a simple program to display the file info of an html file bundled into the application myapp.

My directory structure looks like this:

public 
    -->index.html
go.mod 
go.sum 
myapp
pkgerWalk.go 
-------------------------------------------------------------------------------------------------
pkgerWalk.go  

package main
 
import (
    "fmt"
 
    "github.com/markbates/pkger"
)
/*func doNothing() {
    pkger.Stat("/public/")
}*/
 
func main() {
    fileInfo, err := pkger.Stat("/public/" + "index.html")
    if err != nil {
        fmt.Println(err)
    }
    fmt.Println(fileInfo)
}

Same problem occurs when pkger.Open() is used instead of pkger.Stat().
$ pkger parse
{
 ".": null
}
$ pkger list
pkger
$ go build
$ ./myapp 
could not stat pkger:/public/index.html
<nil>

Go env :
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/username/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/username/go"
GOPROXY=""
GORACE=""
GOROOT="/opt/local/lib/go"
GOTMPDIR=""
GOTOOLDIR="/opt/local/lib/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="/usr/bin/clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/username/project_folder/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8b/yj_ny0zj7cbfv1678cpg1y080000gp/T/go-build616005915=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Workaround**: Uncomment the doNothing() function.

**Comment by markbates** [comment]
https://github.com/markbates/pkger#understanding-the-parser

This works as expected. The `pkger.Include(string) string` function is provided to allow of include files into the binary. It returns the string passed in so you can capture it as a variable and use it later.
