### ISSUE TITLE
Pkger does not return any error/warning when pkger.Open() is unable to open the concatenated file name passed to it.

### ISSUE THREAD

**Issue by snehagundura** [markbates/pkger#46]
It would be helpful if pkger emits a warning when trying pkger.Open(path + filename), either saying "unable to process pkger.Open()" or suggesting to use pkger.Include()

I have a simple program to display the file info of an html file bundled into the application myapp.

My directory structure looks like this:

public 
    -->index.html
go.mod 
go.sum 
myapp
pkgerWalk.go 
package main
 
import (
    "fmt"
 
    "github.com/markbates/pkger"
)
/*func doNothing() {
    pkger.Stat("/public/")
}*/
 
func main() {
    fileInfo, err := pkger.Stat("/public/" + "index.html")
    if err != nil {
        fmt.Println(err)
    }
    fmt.Println(fileInfo)
}

Same problem occurs when pkger.Open() is used instead of pkger.Stat().
$ pkger parse
{
 ".": null
}
$ pkger list
pkger
$ go build
$ ./myapp 
could not stat pkger:/public/index.html
<nil>

Go env :
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/username/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/username/go"
GOPROXY=""
GORACE=""
GOROOT="/opt/local/lib/go"
GOTMPDIR=""
GOTOOLDIR="/opt/local/lib/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="/usr/bin/clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/username/project_folder/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/8b/yj_ny0zj7cbfv1678cpg1y080000gp/T/go-build616005915=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by markbates** [comment]
This works as expected. At runtime the two variables or strings can concated together and produce a string. 

At parse time, static analysis can’t run your code, so it can ONLY detect regular strings literals. You can’t check for this at runtime. 

So while I feel your pain, it is a requirement of static analysis.

**Comment by stephenafamo** [comment]
I just spent a long time trying to figure out why pkger was not packing my files before finding this comment.

It would be really helpful if you could add a very prominent note about this in the Readme.md\

Thanks for your work
