### ISSUE TITLE
using pkger.Apply

### ISSUE THREAD

**Issue by T2RKUS** [markbates/pkger#47]
I had thought that when the pkger.Apply method said "Apply will wrap the current implementation of pkger.Pkger with the new pkg. This allows for layering of pkging.Pkger implementations." I could add my own layer over the memory layer. I have an issue where I want my web server to request static images from the static file server through to my resource database that will return an image from that instead of on disk or in memory through "mem" layer. I want to check for a "public/img" prefix and send it to my resource server otherwise use the mem layer.

However when I do this and return an os.ErrNotExist it doesn't drop down a layer. It seems that Apply can only be called once? The reason I want to do this is that I will have alot of static images and I want to embed them into my key/value db. I just ended up copying part of the mem stuff that returns errors to see if I drops a layer.

```go
func New(info here.Info) (*Pkger, error) {
	f := &Pkger{
		Here: info,
	}
	return f, nil
}

type Pkger struct {
	Here here.Info
}
func (f *Pkger) Current() (here.Info, error) {
	return f.Here, nil
}
func (f *Pkger) Info(p string) (here.Info, error) {
	return here.Info{}, fmt.Errorf("Info: Not Implemented")
}

func (f *Pkger) Parse(p string) (here.Path, error) {
	return f.Here.Parse(p)
}

func (fx *Pkger) Remove(name string) error {
	return fmt.Errorf("Remove: Not Implemented")
}
func (fx *Pkger) RemoveAll(name string) error {
	return fmt.Errorf("RemoveAll: Not Implemented")
}
func (fx *Pkger) Create(name string) (pkging.File, error) {
	return nil, fmt.Errorf("Create: Not Implemented")
}
func (fx *Pkger) MkdirAll(p string, perm os.FileMode) error {
	return fmt.Errorf("MkDirAll: Not Implemented")
}
func (fx *Pkger) Open(name string) (pkging.File, error) {
	return nil, os.ErrNotExist
}
func (fx *Pkger) Stat(name string) (os.FileInfo, error) {
	return nil, os.ErrNotExist
}

func (f *Pkger) Walk(p string, wf filepath.WalkFunc) error {
	return fmt.Errorf("Walk: Not Implemented")
}

func main() {

	pkger.Apply(New(here.Info{}))


	f, err := pkger.Open("/test.txt")
	if err != nil {
		fmt.Println(err)
	} else {
		bytes, _ := ioutil.ReadAll(f)
		fmt.Println(string(bytes))
	}
}
```

**Comment by T2RKUS** [comment]
Thinking more about this, It would probably be better just to just write an implementation of a file server and just call Open from a given pkger...

**Comment by markbates** [comment]
Apply does wrap many pkgers. While I haven’t played with your example, the issue is most likely do to load order or another issue along those lines. 

If no pkger is apply it uses the disk, but if you apply another pkger that become the parent implementation. If you want to call back to disk you should first apply the stdos pkger implementation. 

If you’re trying to use the mem one that pkger built you have to make sure that gets loaded first so yours falls back to it.

**Comment by T2RKUS** [comment]
Thanks, I'll look into that. In the mean time this is working.

```go
type HttpDir string

func (d HttpDir) Open(name string) (http.File, error) {
	log.Printf("FileServer: Requested %s", name)
	if v, ok := filemap[name]; ok {
		log.Printf("FileServer: Found (Resource Server) %s", name)
		err := v.Open()
		if err != nil {
			return nil, err
		}
		return v, nil
	}
	fs := pkger.Dir(string(d))
	file, err := fs.Open(name)
	if os.IsExist(err) {
		log.Printf("FileServer: Found (Pkger) %s", name)
	} else {
		log.Printf("FileServer: Did Not Find File (Pkger) %s", name)
	}
	return file, err
}
```
