### ISSUE TITLE
Increase code coverage to >=80%

### ISSUE THREAD

**Issue by koddr** [markbates/pkger#48]
Hi, @markbates!

I try to [add `pkger` to `awesome-go` list](https://github.com/avelino/awesome-go/pull/2839), but the last stop-thing is code coverage. To add, package's code will be >= 80% coverage, but 56.7% now.

@panjf2000:

> Please check out why some CI checks failed first, besides there are still several sections of report-card doesn't reache 100%, please also resolve those, in the end, please increase your code coverage to >=80%(it is 56.7% now).

Can you please increase this thing? 👍

**Comment by markbates** [comment]
Theyre using flawed metrics. They’re looking at one package results and not the whole project, which is a very poor way to judge any project. That package contains almost no code as it’s mostly used for static analysis in project code and instead pushes almost all work to sub packages. So there’s tests to write, and I, personally, don’t have time to write tests to satisfy their metrics that don’t provide any actual test coverage. If others want to satisfy their conditions, I’ll leave this ticket open. 

--
Mark Bates
