### ISSUE TITLE
A .go file *REQUIRED* at root of module?

### ISSUE THREAD

**Issue by mashaalmemon** [markbates/pkger#49]
Still experiencing the same issue as outlined in #34. @markbates, you mentioned this would be fixed in v0.12.3 in that thread. I'm using v0.12.8

I get error:
```
 "go list -json -find <my_package>: cannot find module providing package <my_package>
```

I addressed this by putting a `dummy.go` file at the root of the module.

Is having a `.go` file at the root of the module, a requirement?

**Comment by markbates** [comment]
It's not a requirement of Pkger, but rather failings with the `go` tooling itself that involves catching STDERR and parsing it.

**Comment by sagikazarmark** [comment]
I'm still experiencing this issue with the latest pkger:

```
can't load package: package github.com/sagikazarmark/modern-go-application: cannot find module providing package github.com/sagikazarmark/modern-go-application
```

Go version:
```
go version go1.13.4 darwin/amd64
```

Putting an empty Go file in the module root solves the issue.

**Comment by hlubek** [comment]
I struggled with this too. It would be great to explain the possible cause of this error.

**Comment by win5do** [comment]
This tool is confusing.
