### ISSUE TITLE
Segmentation violation at parse.go:22 on some specific system configurations

### ISSUE THREAD

**Issue by moqmar** [markbates/pkger#54]
It almost seems like a resurrection of [this Go issue from 2017](https://marcan.st/2017/12/debugging-an-evil-go-runtime-bug/), but I have a problem where [parse.go:22](https://github.com/markbates/pkger/blob/master/here/parse.go#L22) panics with `unexpected fault address 0x... - fatal error: fault - [signal SIGSEGV: segmentation violation ...]`. But, I could only reproduce this on an embedded ARM device running a custom Yocto Project linux distribution. Running the program multiple times leads to multiple different error messages (one time it even worked flawlessly ¯\\\_(ツ)_/¯).

For debugging purposes, I added `fmt.Printf("RegExp: %+v\n", pathrx)` just above that line, yielding in most cases the weird message `RegExp: %!v(PANIC=String method: runtime error: growslice: cap out of range)`, and in other cases just `RegExp: `:
![image](https://user-images.githubusercontent.com/5559994/70889516-1515aa00-1fe3-11ea-93de-88840c18bd5b.png)

**The bad news:** I have no idea how to even start with debugging something like this, or even how to test with different Go versions in Yocto without breaking stuff. So, this could very well already be fixed upstream, but still is a huge problem in my case.
**The good news:** there seems to be a simple workaround for which I'll be opening a PR if you don't mind - just shifting the initialization of the regular expression inside the function is enough to stop this bug from happening.

**Comment by moqmar** [comment]
Just saw #50, I'll be trying if it fixes this issue.

**Comment by markbates** [comment]
@moqmar thanks. if you could fix it at `gobuffalo/here`, that would be great. I need to get back to making #50 pass the tests. thanks for the reminder.
