### ISSUE TITLE
Uses `package main` even with -o

### ISSUE THREAD

**Issue by porridge** [markbates/pkger#56]
Contrary to what [documentation claims](https://github.com/markbates/pkger/blame/master/README.md#L56-L66) the `package` directive is still `main` if I ask `pkger` to write the file in another directory.
```
$ pkger -o config
$ head -n 1 config/pkged.go 
package main
```

**Comment by jwriteclub** [comment]
👍

**Comment by fpaniagua** [comment]
Ran into this issue recently when upgrading, and had to revert to v0.12.8.

Did a git bisect, and it indicated:
https://github.com/markbates/pkger/commit/b334bd73acb5839bc08969a0c85960ef64dca383

Lines 146 to 148 may be reverting name back to `main`.

**Comment by mschristensen** [comment]
👍

**Comment by al45tair** [comment]
Using v0.12.7 appears to avoid this problem (thanks @fpaniagua for doing a bisect).

**Comment by markbates** [comment]
PRs are welcome

**Comment by al45tair** [comment]
@markbates It would help if it was more obvious why b334bd7 does what it does. I'm quite happy to work up a fix if I know what I'm fixing :-)

**Comment by markbates** [comment]
Without digging in my gut is that it is meant to check if the output directory is main and set the name to that regardless. 

--
Mark Bates

**Comment by taiyangc** [comment]
Facing a similar issue here - if the root directory is a module, i.e. is **not** of package `main` and has any `*.go` files under root, `pkger -include xxx` will fail (on package name conflict).

@markbates I don't think the assumption that "check if the output directory is main" is correct for the PR https://github.com/markbates/pkger/pull/53 It should be inspecting the actual output dir's current package name and set it to that, even if at top level, it's not guaranteed to be `main`.

To show how painful it is for me to generate `pkger.go` correctly:
1. Rename all the `*.go`'s package names to `main`.
2. Call `pkger -include xxx`.
3. Change all `*.go` package names back to `<original>`.
4. Rename `pkger.go`'s package name to `<original>`.
5. Build.

---end of rant---

I am providing a fix for both my and OP's problem here: https://github.com/markbates/pkger/pull/80
Thanks for consideration.

**Comment by markbates** [comment]
Thank you everyone for tracking this down and for fixing it. Release in the making.

**Comment by aaahrens** [comment]
Is this fixed? I am having this issue
