### ISSUE TITLE
Middleware config

### ISSUE THREAD

**Issue by PatWie** [markbates/pkger#59]
I appreciate having pkger. Great work! I do not care about the slow speed at the moment.
This new development seems to be a chance to broaden what a packager can do.

I was looking for embedding js, css and html. So far I use a bash script to minify these assets and then embedded them into my binary:

https://github.com/PatWie/digitalmusicstand/blob/master/.drone.yml#L14-L27

Would it be possible to have a pkger config file that contains the intermediate result like ˋpkger listˋ does today? I am thinking about something the Hugo assets pipeline does: concatenate and minify files, scss parsing, ...

This further allows to also encrypt the packed data (I saw a feature request in another similar library during testing different packers) besides caching the absolute file paths.

**Comment by markbates** [comment]
Sorry you don’t like the speed, although without specifics I can’t help you with that, other than to say that PRs are welcome. 

As for the other request, you can use the parser directly https://godoc.org/github.com/markbates/pkger/parser#Parser to return a list of all files to be packed.
