### ISSUE TITLE
New generated code comment has dangling parameter which causes pkged.go to fail to compile.

### ISSUE THREAD

**Issue by swedishborgie** [markbates/pkger#71]
It looks like #69 introduced a Fprintf with an extraneous parameter which is causing generated code to be invalid:

    fmt.Fprintf(f, "// Code generated by pkger; DO NOT EDIT.\n\n", name) // <-- name is extraneous

With Go 1.13 this produces the following code:

    // Code generated by pkger; DO NOT EDIT.

    %!(EXTRA string=main)package main

    import (
	    "github.com/markbates/pkger"
	    "github.com/markbates/pkger/pkging/mem"
    )

    var _ = pkger.Apply(mem.UnmarshalEmbed([]byte(<snip>)))

**Comment by hnnsgstfssn** [comment]
Was noted on review of #69 that it would cause vet errors and then addressed in #70 which was just merged.

**Comment by swedishborgie** [comment]
Yep, confirmed. PR #70 fixes this issue. Closed PR #72. Thanks!
