### ISSUE TITLE
Anyway to use files on disk for development like gobuffalo/packr?

### ISSUE THREAD

**Issue by xDuck** [markbates/pkger#81]
With gobuffalo/packr you can use the actual files on the system for development, allowing you to swap your static file's contents without needing to rebuild. Is there a similar functionality here?

**Comment by markbates** [comment]
That is how Pkger works by default. Unless you’ve run the pkger command and generated the pkged.go file, it will load from disk.

**Comment by xDuck** [comment]
Seems my issue was that I had multiple `pkger.go` files in my project for different directories. Hold-over from migrating from go-bindata. Deleting all of them seems to be working as expected. Thanks!

**Comment by xDuck** [comment]
It would be really neat if there was a command line flag for conditional compilation of the pkger.go file, that way I wouldn't have to delete it if I want to go back and forth between production and dev builds..

https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool

**Comment by markbates** [comment]
PR's are welcome. I'm sure others would love a build tag.

**Comment by xDuck** [comment]
PR made, love the code - It was super easy to figure out
