### ISSUE TITLE
The parser doesn't recognize file names when stored in a variable.

### ISSUE THREAD

**Issue by ramantehlan** [markbates/pkger#88]
`pkger parse` or `pkger list` doesn't work when the file name is stored in a variable. 

```go
var fileName =  "/bin/file.txt"

// This doesn't work 
pkger.Include(fileName)
// This works
pkger.Include("/bin/file.txt")
```

**Comment by Xeoncross** [comment]
It seems a solution is to use `pkger.Include("/bin/file.txt")` for all files you need, then you can use variables elsewhere the program knowing the assets are already loaded.

**Comment by ramantehlan** [comment]
Yup, that's how I did it eventually, but thank you for the reply. :)
